version: "3.7"
services:
  mysql:
    container_name: mysql
    image: mysql
    restart: on-failure:1
    ports:
      - 3306:3306
    env_file: .env
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 1s
      interval: 10s
      retries: 10
      start_period: 15s
  app-run-migrations:
    container_name: app-run-migrations
    build: .
    env_file: .env
    command: ./wait-for-it.sh -t 120 mysql:3306 -- npx sequelize-cli db:migrate
    depends_on:
      - mysql
  test:
    container_name: test
    profiles: ["test"]
    build: .
    env_file: .env.test
    command: ./wait-for-it.sh -t 120 mysql:3306 -- npm run test
    depends_on:
      - mysql
  app:
    container_name: app
    restart: on-failure:3
    build: .
    env_file: .env
    ports:
      - 3000:3000
    external_links:
      - mysql
    depends_on:
      - mysql
      - app-run-migrations
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 10s
      timeout: 1s
      retries: 5
      start_period: 15s
    command: ./wait-for-it.sh -t 120 mysql:3306 -- npm run start
